---
- name: HKEX RHEL Containment Main Entry Point
  hosts: all
  gather_facts: yes
  vars:
    aap_ip: "10.211.55.3"
    dns_ip: "10.211.55.1"
    # Extra variables from API
    containment_action: "{{ containment_action }}"
    profile: "{{ profile | default('') }}"
    outbound_whitelist: "{{ outbound_whitelist | default([]) }}"
    hostnames: "{{ hostnames | default([]) }}"
    verification_list: "{{ verification_list | default([]) }}"
    # Process inventory information
    all_inventories_json: "{{ all_inventories | default('{}') }}"
    processed_inventories: "{{ all_processed_inventories | default([]) }}"
    # Default variables
    backup_path: "/root/"
    default_inbound_whitelist:
      - ip: "{{ aap_ip }}"
        port: 22
        protocol: "tcp"
    default_outbound_whitelist:
      - ip: "{{ dns_ip }}"
        port: 53
        protocol: "tcp"
      - ip: "{{ dns_ip }}"
        port: 53
        protocol: "udp"

  pre_tasks:
    - name: Validate action variable
      fail:
        msg: "Action must be either 'containment' or 'resume'"
      when: containment_action not in ['containment', 'resume']

    - name: Load all inventories data if provided
      set_fact:
        all_inventories_data: "{{ all_inventories_json | from_json }}"
      when: all_inventories_json != '{}'
      ignore_errors: yes

    - name: Display inventory information
      debug:
        msg:
          - "Current host: {{ inventory_hostname }}"
          - "Processed inventories: {{ processed_inventories }}"
      
    - name: Find inventory data for current host
      set_fact:
        current_inventory: "{{ item }}"
      when: inventory_hostname in item.hosts
      loop: "{{ processed_inventories }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display current inventory data
      debug:
        var: current_inventory
      when: current_inventory is defined

  tasks:
    - name: Run containment role
      include_role:
        name: containment
      when:
        - containment_action == 'containment'

    - name: Run Resume role
      include_role:
        name: resume
      when:
        - containment_action == 'resume'