---
- name: HKEX RHEL Containment Main Entry Point
  hosts: all  # Use 'all' since limit will filter hosts
  gather_facts: yes
  vars:
    # Extra variables from XSOAR frontend via AAP API
    containment_action: "{{ containment_action }}"  # Renamed from 'action' to avoid reserved name warning
    profile: "{{ profile | default('') }}"          # 'FULL', 'PARTIAL', 'REBUILT' (for containment)
    inbound_whitelist: "{{ inbound_whitelist | default([]) }}"
    outbound_whitelist: "{{ outbound_whitelist | default([]) }}"
    hostnames: "{{ hostnames | default([]) }}"      # List of hostnames from extra vars
    verification_list: "{{ verification_list | default([]) }}"  # List of IPs to verify outgoing traffic
    # Default variables
    backup_path: "/var/backup/hkex"
    default_inbound_whitelist: []
    default_outbound_whitelist: []

  pre_tasks:
    - name: Validate action variable
      fail:
        msg: "Action must be either 'containment' or 'resume'"
      when: containment_action not in ['containment', 'resume']

  tasks:
    - name: Run containment role for RHEL 9
      include_role:
        name: containment
        tasks_from: rhel9_containment.yml
      when:
        - containment_action == 'containment'
        - ansible_distribution_major_version == '9'

#    - name: Run resume role (not updated here as focus is RHEL 9 containment)
#      include_role:
#        name: resume
#      when: containment_action == 'resume'