---
- name: HKEX RHEL Containment Main Entry Point
  hosts: all
  gather_facts: yes
  vars:
    aap_ip: "192.168.122.11"
    dns_ip: "192.168.122.12"
    # Extra variables from API
    containment_action: "{{ containment_action }}"
    profile: "{{ profile | default('') }}"
    outbound_whitelist: "{{ outbound_whitelist | default([]) }}"
    hostnames: "{{ hostnames | default([]) }}"
    verification_list: "{{ verification_list | default([]) }}"
    # Default variables
    backup_path: "/root/"
    default_inbound_whitelist:
      - ip: "{{ aap_ip }}"
        port: 22
        protocol: "tcp"
    default_outbound_whitelist:
      - ip: "{{ dns_ip }}"
        port: 53
        protocol: "tcp"
      - ip: "{{ dns_ip }}"
        port: 53
        protocol: "udp"

  pre_tasks:
    - name: Validate action variable
      fail:
        msg: "Action must be either 'containment' or 'resume'"
      when: containment_action not in ['containment', 'resume']

  tasks:
    - name: Run containment role for RHEL 9
      include_role:
        name: containment
        tasks_from: rhel9_containment.yml
      when:
        - containment_action == 'containment'
        - ansible_distribution_major_version == '9'
