---
- name: Find latest backup
  find:
    paths: "{{ backup_path }}"
    patterns: "{{ profile }}-{{ ansible_date_time.date }}"
    file_type: directory
  register: backup_files

- name: Read saved nftables service state
  ansible.builtin.slurp:
    src: "{{ backup_path }}/{{ profile }}-{{ ansible_date_time.date }}/nftables_service_state"
  register: nftables_saved_state
  failed_when: false
  when: backup_files.matched > 0

- name: Set latest backup path
  set_fact:
    latest_backup: "{{ (backup_files.files | sort(attribute='mtime', reverse=True) | first).path }}"
  when: backup_files.matched > 0

- name: Copy nftables from latest backup
  copy:
    src: "{{ latest_backup }}/nftables.conf"
    dest: "/etc/sysconfig/nftables.conf"
    remote_src: yes
  when: backup_files.matched > 0

- name: Get current nftables service state
  ansible.builtin.command: systemctl is-active nftables.service
  register: nftables_current_state
  changed_when: false
  failed_when: false

# If the service was initially inactive but is now active, stop it
- name: Stop nftables service if it was initially inactive
  ansible.builtin.service:
    name: nftables
    state: stopped
  when: 
    - nftables_saved_state is defined 
    - nftables_saved_state.content is defined
    - (nftables_saved_state.content | b64decode | trim) == 'inactive' or (nftables_saved_state.content | b64decode | trim) == 'unknown'
    - nftables_current_state.stdout == 'active'

- name: Apply restored nftables rules
  service:
    name: nftables
    state: reloaded
  async: 60
  poll: 0
  register: nftables_result
  when:
    - backup_files.matched > 0
    - nftables_saved_state is defined 
    - nftables_saved_state.content is defined
    - (nftables_saved_state.content | b64decode | trim) == 'active'

- name: check restart nftables status
  async_status:
    jid: "{{ nftables_result.ansible_job_id }}"
  register: nftables_restore_result
  until: nftables_restore_result.finished
  retries: 30
  when:
    - backup_files.matched > 0
    - nftables_saved_state is defined 
    - nftables_saved_state.content is defined
    - (nftables_saved_state.content | b64decode | trim) == 'active'

- name: Remove backup after successful resume
  file:
    path: "{{ latest_backup }}"
    state: absent
  when: 
  - backup_files.matched > 0