download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/awx-awx-24.6.1.tar.gz
format_version: 1.0.0
name: awx
namespace: awx
server: https://galaxy.ansible.com/api/
signatures: []
version: 24.6.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/awx/awx/versions/24.6.1/
