---
- name: Include RHEL 7 containment tasks
  include_tasks: rhel7_containment.yml
  when: ansible_distribution_major_version == '7' or os_type == 'rhel7'

- name: Include RHEL 8 containment tasks
  include_tasks: rhel8_containment.yml
  when: ansible_distribution_major_version == '8' or os_type == 'rhel8'

- name: Include RHEL 9 containment tasks
  include_tasks: rhel9_containment.yml
  when: ansible_distribution_major_version == '9' or os_type == 'rhel9'